// Generated by gencpp from file behavior_tree_msgs/Active.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MSGS_MESSAGE_ACTIVE_H
#define BEHAVIOR_TREE_MSGS_MESSAGE_ACTIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree_msgs
{
template <class ContainerAllocator>
struct Active_
{
  typedef Active_<ContainerAllocator> Type;

  Active_()
    : active(false)
    , id(0)  {
    }
  Active_(const ContainerAllocator& _alloc)
    : active(false)
    , id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;

   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::behavior_tree_msgs::Active_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree_msgs::Active_<ContainerAllocator> const> ConstPtr;

}; // struct Active_

typedef ::behavior_tree_msgs::Active_<std::allocator<void> > Active;

typedef boost::shared_ptr< ::behavior_tree_msgs::Active > ActivePtr;
typedef boost::shared_ptr< ::behavior_tree_msgs::Active const> ActiveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree_msgs::Active_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree_msgs::Active_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree_msgs::Active_<ContainerAllocator1> & lhs, const ::behavior_tree_msgs::Active_<ContainerAllocator2> & rhs)
{
  return lhs.active == rhs.active &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree_msgs::Active_<ContainerAllocator1> & lhs, const ::behavior_tree_msgs::Active_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_msgs::Active_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_msgs::Active_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_msgs::Active_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_msgs::Active_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_msgs::Active_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_msgs::Active_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree_msgs::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c07e551e186876ca3af3ff1a8f330ec9";
  }

  static const char* value(const ::behavior_tree_msgs::Active_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc07e551e186876caULL;
  static const uint64_t static_value2 = 0x3af3ff1a8f330ec9ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree_msgs::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree_msgs/Active";
  }

  static const char* value(const ::behavior_tree_msgs::Active_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree_msgs::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool active\n"
"int64 id\n"
;
  }

  static const char* value(const ::behavior_tree_msgs::Active_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree_msgs::Active_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Active_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree_msgs::Active_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree_msgs::Active_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MSGS_MESSAGE_ACTIVE_H
