// Generated by gencpp from file behavior_tree_msgs/BehaviorTreeCommand.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MSGS_MESSAGE_BEHAVIORTREECOMMAND_H
#define BEHAVIOR_TREE_MSGS_MESSAGE_BEHAVIORTREECOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree_msgs
{
template <class ContainerAllocator>
struct BehaviorTreeCommand_
{
  typedef BehaviorTreeCommand_<ContainerAllocator> Type;

  BehaviorTreeCommand_()
    : condition_name()
    , status(0)  {
    }
  BehaviorTreeCommand_(const ContainerAllocator& _alloc)
    : condition_name(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _condition_name_type;
  _condition_name_type condition_name;

   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorTreeCommand_

typedef ::behavior_tree_msgs::BehaviorTreeCommand_<std::allocator<void> > BehaviorTreeCommand;

typedef boost::shared_ptr< ::behavior_tree_msgs::BehaviorTreeCommand > BehaviorTreeCommandPtr;
typedef boost::shared_ptr< ::behavior_tree_msgs::BehaviorTreeCommand const> BehaviorTreeCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator1> & lhs, const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator2> & rhs)
{
  return lhs.condition_name == rhs.condition_name &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator1> & lhs, const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88f8877408328a1537655cc1377c588d";
  }

  static const char* value(const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88f8877408328a15ULL;
  static const uint64_t static_value2 = 0x37655cc1377c588dULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree_msgs/BehaviorTreeCommand";
  }

  static const char* value(const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string condition_name\n"
"int8 status\n"
;
  }

  static const char* value(const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.condition_name);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorTreeCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree_msgs::BehaviorTreeCommand_<ContainerAllocator>& v)
  {
    s << indent << "condition_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.condition_name);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MSGS_MESSAGE_BEHAVIORTREECOMMAND_H
