// Generated by gencpp from file behavior_tree_msgs/Status.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MSGS_MESSAGE_STATUS_H
#define BEHAVIOR_TREE_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : status(0)
    , id(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : status(0)
    , id(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;

   typedef uint64_t _id_type;
  _id_type id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FAILURE)
  #undef FAILURE
#endif
#if defined(_WIN32) && defined(RUNNING)
  #undef RUNNING
#endif
#if defined(_WIN32) && defined(SUCCESS)
  #undef SUCCESS
#endif

  enum {
    FAILURE = 0,
    RUNNING = 1,
    SUCCESS = 2,
  };


  typedef boost::shared_ptr< ::behavior_tree_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::behavior_tree_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::behavior_tree_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::behavior_tree_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree_msgs::Status_<ContainerAllocator1> & lhs, const ::behavior_tree_msgs::Status_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree_msgs::Status_<ContainerAllocator1> & lhs, const ::behavior_tree_msgs::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff468a49be3012e35a4261c2990f465a";
  }

  static const char* value(const ::behavior_tree_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff468a49be3012e3ULL;
  static const uint64_t static_value2 = 0x5a4261c2990f465aULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree_msgs/Status";
  }

  static const char* value(const ::behavior_tree_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 FAILURE=0\n"
"int8 RUNNING=1\n"
"int8 SUCCESS=2\n"
"\n"
"int8 status\n"
"uint64 id\n"
;
  }

  static const char* value(const ::behavior_tree_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree_msgs::Status_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MSGS_MESSAGE_STATUS_H
